# Generated by Django 2.2 on 2019-04-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190408_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ('created', 'user'), 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
