# Generated by Django 2.2 on 2019-04-13 20:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190408_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.Accounts')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('created', 'account'),
            },
        ),
    ]
